/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f7",
        "slate-deep": "#0F172A",
        "slate-muted": "#1E293B",
        "action-orange": "#F28C28",
        primary: "#944a00",
        "primary-container": "#e67e22",
        "on-primary": "#ffffff",
        "on-primary-container": "#502600",
        secondary: "#565e74",
        "on-surface": "#1b1c1b",
        "surface-variant": "#e5e2e0",
        "surface-white": "#FFFFFF",
        "surface-container-low": "#f6f3f1",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0edeb",
        "surface-container-high": "#eae8e6",
        "outline-variant": "#dcc1b1",
        "primary-fixed-dim": "#ffb783",
        "secondary-fixed-dim": "#bec6e0",
      },
      spacing: {
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "40px",
        xl: "80px",
        gutter: "24px",
        "container-max": "1280px",
      },
      maxWidth: { "container-max": "1280px" },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
